import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Welcome to my blog!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div class="hero min-h-screen">
          <div class="hero-content">
            <div class="max-w-3xl min-w-fit text-center">
              <h1 class="text-3xl font-bold text-center">
                Hi there! My name is Phúc (Scott) Nguyễn.
              </h1>
              <p class="max-w-xl py-8 text-left">
                This is a fun little expriment that I want to create, by
                practicing and using a few specific frameworks and libraries -
                as a <b>Front-end Web developer</b>. Thank you so much for
                visting!
              </p>
              <button class="btn btn-secondary btn-outline">
                Read my blogs
              </button>
              <button class="ml-6 btn btn-secondary btn-outline">
                What's under the hood
              </button>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
