import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Welcome to my blog!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div class="hero min-h-screen">
          <div class="hero-content">
            <div class="max-w-lg text-center">
              <h1 class="text-5xl font-bold text-left">Welcome to my blog!</h1>
              <p class="py-7 text-left">
                Provident cupiditate voluptatem et in. Quaerat fugiat ut
                assumenda excepturi exercitationem quasi. In deleniti eaque aut
                repudiandae et a id nisi.
              </p>
              <button class="btn btn-outline">Get Started</button>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
